AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  plowterra-api

Globals:
  Function:
    Timeout: 10
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Events:
        Express:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  ExpressApi:
    Description: API Gateway endpoint URL for Prod stage for Express function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ExpressFunction:
    Description: Express Lambda Function ARN
    Value: !GetAtt ExpressFunction.Arn
  ExpressFunctionIamRole:
    Description: Implicit IAM Role created for Express function
    Value: !GetAtt ExpressFunctionRole.Arn
